FROM alascu/metalib:base_gmp

# Pull repo
RUN \
    git clone https://github.com/PollyLabs/library-metamorphic-testing.git

# Set workdir to repo location
WORKDIR /home/library-metamorphic-testing

# Setup output folder and link
RUN mkdir /output && ln -s /output ./output

# Copy config file template over and update paths
RUN \
    sed 's|<work_dir>|'`pwd`'\/|' < ./config_files/config.yaml.template \
        > ./config_files/config_gmp_rational.yaml && \
    sed -i 's|<lib>|gmp_rational|' ./config_files/config_gmp_rational.yaml && \
    sed -i 's|lib_path:.*|lib_path: "/home/gmp/.libs/"|' ./config_files/config_gmp_rational.yaml && \
    sed -i 's|lib_build_dir:.*|lib_build_dir: "/home/gmp/"|' ./config_files/config_gmp_rational.yaml && \
    sed -i 's|test_compile_bin:.*|test_compile_bin: "./compile_gmp.sh"|' ./config_files/config_gmp_rational.yaml && \
    sed -i 's|default_timeout:.*|default_timeout: 120|' ./config_files/config_gmp_rational.yaml
#    sed -i 's|api_fuzzer_<name>|api_fuzzer_gmp|' ./config_files/config_gmp.yaml && \
#    sed -i 's|meta_tests_<lib>|meta_tests_gmp|' ./config_files/config_gmp.yaml && \

# Build project
RUN mkdir build && cd build && cmake .. && make

# Set command to run experiments
CMD ["python3.7", "./scripts/meta_runner.py", "--config-file", "./config_files/config_gmp_rational.yaml", "continuous", "--append-id"]

