FROM alascu/metalib:base_boost

# Pull repo
RUN \
    git clone https://github.com/PollyLabs/library-metamorphic-testing.git

# Set workdir to repo location
WORKDIR /home/library-metamorphic-testing

# Setup output folder and link
RUN mkdir /output && ln -s /output ./output

# Copy config file template over and update paths
RUN \
    sed 's|<work_dir>|'`pwd`'\/|' < ./config_files/config.yaml.template \
        > ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|<lib>|boost_multiprecision|' ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|lib_path:.*|lib_path: "/home/boost/stage/lib"|' ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|include_path:.*|include_path: "/home/boost"|' ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|lib_build_dir:.*|lib_build_dir: "/home/boost"|' ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|test_compile_bin:.*|test_compile_bin: "./compile_boost.sh"|' ./config_files/config_boost_multiprecision.yaml && \
    sed -i 's|default_timeout:.*|default_timeout: 120|' ./config_files/config_boost_multiprecision.yaml && \
    ln -s `pwd`/scripts/compile/compile_boost.sh ./out/compile_boost.sh

# Build project
RUN mkdir build && cd build && cmake .. && make -j4

# Set command to run experiments
CMD ["python3.7", "./scripts/meta_runner.py", "--config-file", "./config_files/config_boost_multiprecision.yaml", "continuous", "--append-id"]

