FROM alascu/metalib:base
# Get and build gmp
RUN \
    apt-get install -y wget bzip2 m4 && \
    wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2 && \
    tar xjf gmp-6.1.2.tar.bz2 && mv gmp-6.1.2 gmp && cd gmp && \
    ./configure --enable-cxx && make -j6
