FROM alascu/metalib:base

# Get and build z3 with coverage info
RUN \ 
    git clone https://github.com/Z3Prover/z3.git && cd z3 && \
    python3.7 scripts/mk_make.py && cd build && \
    CXXFLAGS="-ftest-coverage -fprofile-arcs" make -j6
