FROM alascu/metalib:base
# Get and build boost
RUN \
    apt-get install -y wget bzip2 m4 && \
    wget https://dl.bintray.com/boostorg/beta/1.70.0.beta1/source/boost_1_70_0_b1.tar.bz2 && \
    tar xjf boost_1_70_0_b1.tar.bz2 && mv boost_1_70_0 boost && cd boost && \
    ./bootstrap.sh &&  ./b2 -j4
