FROM alascu/metalib:base_clang_8

# Get and build isl with coverage info
RUN \
    apt-get install -y automake libtool libgmp-dev llvm libclang-dev && \
    pip3 install pyyaml && \
    git clone git://repo.or.cz/isl.git && \
    cd isl && git checkout maint && ./autogen.sh && \
    CFLAGS="-fprofile-arcs -ftest-coverage" ./configure \
        --with-clang=system --prefix=`pwd`/../isl-install && \
    make -j6 && make install && cd .. && rm -rf isl

RUN \
    git clone --recursive https://github.com/0152la/SpecAST && cd SpecAST && \
    cd third_party/library-metamorphic-testing/ && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DMETALIB_LIB_ONLY=ON -DYAML_BUILD_SHARED_LIBS=ON .. && \
    make -j4 && cd ../../../ && mkdir libs && \
    ln -s `pwd`/third_party/library-metamorphic-testing/build/libmetalib_fuzz.so ./libs && \
    mkdir build && cd build && \
    Clang_DIR=/home/llvm-install/lib/cmake/clang \
        cmake -G "Ninja" \
            -DCMAKE_C_COMPILER=/home/llvm-install/bin/clang \
            -DCMAKE_CXX_COMPILER=/home/llvm-install/bin/clang++ .. && \
    ninja -j4
