FROM alascu/metalib:base_clang

# Get and build isl with coverage info
RUN \
    apt-get install -y automake libtool libgmp-dev && \
    pip3 install pyyaml && \
    git clone git://repo.or.cz/isl.git && \
    cd isl && git checkout maint && ./autogen.sh && \
    CFLAGS="-fprofile-arcs -ftest-coverage" ./configure \
        --prefix=$(readlink -f $(pwd)/../isl-install) && \
    make -j6 && make install && cd .. && rm -rf isl

RUN \
    apt-get install -y pkg-config && \
    git clone --recursive https://github.com/0152la/SpecAST && cd SpecAST && \
    cd third_party/library-metamorphic-testing/ && mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DMETALIB_LIB_ONLY=ON -DYAML_BUILD_SHARED_LIBS=ON .. && \
    make -j4 && cd ../../../ && mkdir libs && \
    ln -s `pwd`/third_party/library-metamorphic-testing/build/libmetalib_fuzz.so ./libs && \
    mkdir build && cd build && \
    Clang_DIR=/home/llvm-install/lib/cmake/clang \
        cmake -G "Ninja" \
            -DCMAKE_C_COMPILER=/home/llvm-install/bin/clang \
            -DCMAKE_CXX_COMPILER=/home/llvm-install/bin/clang++ .. && \
    ninja -j4

RUN \
    cd SpecAST && \
    curl www.doc.ic.ac.uk/~al2510/SpecASTInputs/isl_point.tar --output isl_point.tar && \
    tar -xf isl_point.tar && rm isl_point.tar && cd isl_point && \
    mkdir build && cd build && \
    PKG_CONFIG_PATH=/home/isl-install/lib/pkgconfig \
        cmake -G Ninja -DLLVM_INSTALL_LOC=/home/llvm-install .. && \
    cd ../../ && ln -s ./isl_point/build/compile_commands.json
